pipeline {
    agent any 
    environment {
        DB_URL = "43.205.210.118"
    }

    stages{
        stage('BUILD') {
            steps{
                 sh '''
                    sleep 5
                    echo "This is a BUILD stage"
                '''
            }
        }

        stage('TEST') {
            steps {
                sh '''
                    sleep 6
                    echo "This is a TEST stage"
                '''
            }
        }

        stage('DEPLOY') {
            steps{
                sh '''
                    sleep 5
                    echo "This is a DEPLOY stage"
                '''
            }
        }
    }
}

